In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
stock = yf.Ticker("AAPL")

data = stock.history(period="2y")

data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-09-17 00:00:00-04:00,213.960196,215.100650,212.720566,214.991562,45519300,0.0,0.0
2024-09-18 00:00:00-04:00,215.745257,220.862454,215.735330,218.859207,59894900,0.0,0.0
2024-09-19 00:00:00-04:00,223.123527,227.913460,222.766513,226.971329,66781300,0.0,0.0
2024-09-20 00:00:00-04:00,228.062236,231.156349,225.731725,226.306915,318679900,0.0,0.0
2024-09-23 00:00:00-04:00,225.454025,227.546522,223.936719,224.591248,54146000,0.0,0.0

In [3]:
data["Daily_Return"] = data["Close"].pct_change()

data["Price_Change"] = data["Close"] - data["Open"]

data["Price_Change_Pct"] = (
    data["Close"] - data["Open"]
) / data["Open"]

data["High_Low_Range"] = (
    data["High"] - data["Low"]
) / data["Close"]

data[[
    "Open",
    "High",
    "Low",
    "Close",
    "Daily_Return",
    "Price_Change",
    "Price_Change_Pct",
    "High_Low_Range"
]].tail()

,Open,High,Low,Close,Daily_Return,Price_Change,Price_Change_Pct,High_Low_Range
Date,,,,,,,,
2026-09-11 00:00:00-04:00,327.450012,336.220001,326.299988,332.269989,0.017454,4.819977,0.014720,0.029855
2026-09-14 00:00:00-04:00,334.790009,335.500000,331.339996,333.079987,0.002438,-1.710022,-0.005108,0.012490
2026-09-15 00:00:00-04:00,330.140015,331.779999,328.350006,331.339996,-0.005224,1.199982,0.003635,0.010352
2026-09-16 00:00:00-04:00,332.529999,335.480011,330.700012,332.410004,0.003229,-0.119995,-0.000361,0.014380
2026-09-17 00:00:00-04:00,334.755005,335.579987,330.193695,333.070007,0.001986,-1.684998,-0.005034,0.016172

In [4]:
data["MA_5"] = data["Close"].rolling(window=5).mean()
data["MA_20"] = data["Close"].rolling(window=20).mean()
data["MA_50"] = data["Close"].rolling(window=50).mean()

data["Price_to_MA20"] = data["Close"] / data["MA_20"]
data["Price_to_MA50"] = data["Close"] / data["MA_50"]

data[[
    "Close",
    "MA_5",
    "MA_20",
    "MA_50",
    "Price_to_MA20",
    "Price_to_MA50"
]].tail()

,Close,MA_5,MA_20,MA_50,Price_to_MA20,Price_to_MA50
Date,,,,,,
2026-09-11 00:00:00-04:00,332.269989,322.073999,316.625998,317.830374,1.049408,1.045432
2026-09-14 00:00:00-04:00,333.079987,324.695996,317.983498,318.324693,1.047476,1.046353
2026-09-15 00:00:00-04:00,331.339996,327.719995,319.270998,318.703681,1.037802,1.039649
2026-09-16 00:00:00-04:00,332.410004,331.133997,320.389998,319.144035,1.037517,1.041567
2026-09-17 00:00:00-04:00,333.070007,332.433997,321.201999,319.543036,1.036949,1.042332

In [5]:
data["Return_5D"] = data["Close"].pct_change(periods=5)

data["Return_20D"] = data["Close"].pct_change(periods=20)

data["Momentum_10D"] = (
    data["Close"] - data["Close"].shift(10)
)

data[[
    "Close",
    "Return_5D",
    "Return_20D",
    "Momentum_10D"
]].tail()

                                Close  Return_5D  Return_20D  Momentum_10D
Date
2026-09-11 00:00:00-04:00  332.269989   0.012370    0.088482     17.690002
2026-09-14 00:00:00-04:00  333.079987   0.040973    0.088746     13.379974
2026-09-15 00:00:00-04:00  331.339996   0.047815    0.084263     14.489990
2026-09-16 00:00:00-04:00  332.410004   0.054132    0.072187      7.279999
2026-09-17 00:00:00-04:00  333.070007   0.019904    0.051258      8.110016

In [6]:
data["Volatility_5D"] = data["Daily_Return"].rolling(window=5).std()

data["Volatility_20D"] = data["Daily_Return"].rolling(window=20).std()

data[[
    "Daily_Return",
    "Volatility_5D",
    "Volatility_20D"
]].tail()

                           Daily_Return  Volatility_5D  Volatility_20D
Date
2026-09-11 00:00:00-04:00      0.017454       0.024042        0.015035
2026-09-14 00:00:00-04:00      0.002438       0.018626        0.015034
2026-09-15 00:00:00-04:00     -0.005224       0.017049        0.015140
2026-09-16 00:00:00-04:00      0.003229       0.016155        0.014942
2026-09-17 00:00:00-04:00      0.001986       0.008264        0.014306

In [7]:
data["Volume_MA_20"] = data["Volume"].rolling(window=20).mean()

data["Volume_Ratio"] = (
    data["Volume"] / data["Volume_MA_20"]
)

data[[
    "Volume",
    "Volume_MA_20",
    "Volume_Ratio"
]].tail()

                             Volume  Volume_MA_20  Volume_Ratio
Date
2026-09-11 00:00:00-04:00  50716900    42533320.0      1.192404
2026-09-14 00:00:00-04:00  39269100    43085305.0      0.911427
2026-09-15 00:00:00-04:00  31748200    42764250.0      0.742400
2026-09-16 00:00:00-04:00  35920400    41889045.0      0.857513
2026-09-17 00:00:00-04:00   8019896    39764759.8      0.201684

In [8]:
data["High_Volume_Flag"] = (
    data["Volume_Ratio"] > 1.5
).astype(int)

data[[
    "Volume_Ratio",
    "High_Volume_Flag"
]].tail()

                           Volume_Ratio  High_Volume_Flag
Date
2026-09-11 00:00:00-04:00      1.192404                 0
2026-09-14 00:00:00-04:00      0.911427                 0
2026-09-15 00:00:00-04:00      0.742400                 0
2026-09-16 00:00:00-04:00      0.857513                 0
2026-09-17 00:00:00-04:00      0.201684                 0

In [9]:
delta = data["Close"].diff()

gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)

average_gain = gain.rolling(window=14).mean()
average_loss = loss.rolling(window=14).mean()

relative_strength = average_gain / average_loss

data["RSI_14"] = (
    100 - (100 / (1 + relative_strength))
)

data[["Close", "RSI_14"]].tail()

                                Close     RSI_14
Date
2026-09-11 00:00:00-04:00  332.269989  70.618906
2026-09-14 00:00:00-04:00  333.079987  70.523448
2026-09-15 00:00:00-04:00  331.339996  68.906524
2026-09-16 00:00:00-04:00  332.410004  67.484315
2026-09-17 00:00:00-04:00  333.070007  67.200010

In [10]:
ema_12 = data["Close"].ewm(
    span=12,
    adjust=False
).mean()

ema_26 = data["Close"].ewm(
    span=26,
    adjust=False
).mean()

data["MACD"] = ema_12 - ema_26

data["MACD_Signal"] = data["MACD"].ewm(
    span=9,
    adjust=False
).mean()

data["MACD_Histogram"] = (
    data["MACD"] - data["MACD_Signal"]
)

data[[
    "Close",
    "MACD",
    "MACD_Signal",
    "MACD_Histogram"
]].tail()

                                Close      MACD  MACD_Signal  MACD_Histogram
Date
2026-09-11 00:00:00-04:00  332.269989  3.265371     1.950648        1.314722
2026-09-14 00:00:00-04:00  333.079987  3.970020     2.354523        1.615497
2026-09-15 00:00:00-04:00  331.339996  4.338051     2.751228        1.586823
2026-09-16 00:00:00-04:00  332.410004  4.662314     3.133446        1.528869
2026-09-17 00:00:00-04:00  333.070007  4.915885     3.489933        1.425952

In [11]:
data["Price_Range"] = (
    data["High"] - data["Low"]
) / data["Close"]

data[[
    "High",
    "Low",
    "Close",
    "Price_Range"
]].tail()

                                 High         Low       Close  Price_Range
Date
2026-09-11 00:00:00-04:00  336.220001  326.299988  332.269989     0.029855
2026-09-14 00:00:00-04:00  335.500000  331.339996  333.079987     0.012490
2026-09-15 00:00:00-04:00  331.779999  328.350006  331.339996     0.010352
2026-09-16 00:00:00-04:00  335.480011  330.700012  332.410004     0.014380
2026-09-17 00:00:00-04:00  335.579987  330.193695  333.070007     0.016172

In [12]:
data["Open_Close_Return"] = (
    data["Close"] - data["Open"]
) / data["Open"]

data[[
    "Open",
    "Close",
    "Open_Close_Return"
]].tail()

                                 Open       Close  Open_Close_Return
Date
2026-09-11 00:00:00-04:00  327.450012  332.269989           0.014720
2026-09-14 00:00:00-04:00  334.790009  333.079987          -0.005108
2026-09-15 00:00:00-04:00  330.140015  331.339996           0.003635
2026-09-16 00:00:00-04:00  332.529999  332.410004          -0.000361
2026-09-17 00:00:00-04:00  334.755005  333.070007          -0.005034

In [13]:
data["High_Low_Pct"] = (
    data["High"] - data["Low"]
) / data["Low"]

data[[
    "High",
    "Low",
    "High_Low_Pct"
]].tail()

                                 High         Low  High_Low_Pct
Date
2026-09-11 00:00:00-04:00  336.220001  326.299988      0.030402
2026-09-14 00:00:00-04:00  335.500000  331.339996      0.012555
2026-09-15 00:00:00-04:00  331.779999  328.350006      0.010446
2026-09-16 00:00:00-04:00  335.480011  330.700012      0.014454
2026-09-17 00:00:00-04:00  335.579987  330.193695      0.016313

In [15]:
feature_columns = [
    "Close",
    "Daily_Return",
    "MA_5",
    "MA_20",
    "MA_50",
    "Price_to_MA20",
    "Price_to_MA50",
    "Return_5D",
    "Return_20D",
    "Momentum_10D",
    "Volatility_5D",
    "Volatility_20D",
    "Volume_Ratio",
    "High_Volume_Flag",
    "RSI_14",
    "MACD",
    "MACD_Signal",
    "MACD_Histogram",
    "Price_Range",
    "Open_Close_Return",
    "High_Low_Pct"
]

data[feature_columns].tail()

,Close,Daily_Return,MA_5,MA_20,MA_50,Price_to_MA20,Price_to_MA50,Return_5D,Return_20D,Momentum_10D,...,Volatility_20D,Volume_Ratio,High_Volume_Flag,RSI_14,MACD,MACD_Signal,MACD_Histogram,Price_Range,Open_Close_Return,High_Low_Pct
Date,,,,,,,,,,,,,,,,,,,,,
2026-09-11 00:00:00-04:00,332.269989,0.017454,322.073999,316.625998,317.830374,1.049408,1.045432,0.012370,0.088482,17.690002,...,0.015035,1.192404,0,70.618906,3.265371,1.950648,1.314722,0.029855,0.014720,0.030402
2026-09-14 00:00:00-04:00,333.079987,0.002438,324.695996,317.983498,318.324693,1.047476,1.046353,0.040973,0.088746,13.379974,...,0.015034,0.911427,0,70.523448,3.970020,2.354523,1.615497,0.012490,-0.005108,0.012555
2026-09-15 00:00:00-04:00,331.339996,-0.005224,327.719995,319.270998,318.703681,1.037802,1.039649,0.047815,0.084263,14.489990,...,0.015140,0.742400,0,68.906524,4.338051,2.751228,1.586823,0.010352,0.003635,0.010446
2026-09-16 00:00:00-04:00,332.410004,0.003229,331.133997,320.389998,319.144035,1.037517,1.041567,0.054132,0.072187,7.279999,...,0.014942,0.857513,0,67.484315,4.662314,3.133446,1.528869,0.014380,-0.000361,0.014454
2026-09-17 00:00:00-04:00,333.070007,0.001986,332.433997,321.201999,319.543036,1.036949,1.042332,0.019904,0.051258,8.110016,...,0.014306,0.201684,0,67.200010,4.915885,3.489933,1.425952,0.016172,-0.005034,0.016313

In [16]:
missing_values = data.isnull().sum()

missing_values = missing_values[
    missing_values > 0
].sort_values(ascending=False)

missing_values

MA_50             49
Price_to_MA50     49
Return_20D        20
Volatility_20D    20
MA_20             19
Price_to_MA20     19
Volume_MA_20      19
Volume_Ratio      19
RSI_14            14
Momentum_10D      10
Return_5D          5
Volatility_5D      5
MA_5               4
Daily_Return       1
dtype: int64

In [17]:
data_clean = data.dropna().copy()

print("Original shape:", data.shape)
print("Cleaned shape:", data_clean.shape)
print("Remaining missing values:", data_clean.isnull().sum().sum())

Original shape: (502, 31)
Cleaned shape: (453, 31)
Remaining missing values: 0

In [18]:
data_clean[feature_columns].head()

,Close,Daily_Return,MA_5,MA_20,MA_50,Price_to_MA20,Price_to_MA50,Return_5D,Return_20D,Momentum_10D,...,Volatility_20D,Volume_Ratio,High_Volume_Flag,RSI_14,MACD,MACD_Signal,MACD_Histogram,Price_Range,Open_Close_Return,High_Low_Pct
Date,,,,,,,,,,,,,,,,,,,,,
2024-11-25 00:00:00-05:00,231.192245,0.013051,228.053024,225.194895,226.232597,1.026632,1.021923,0.021270,-0.001173,8.577759,...,0.010810,1.937769,1,69.706490,0.658897,0.033839,0.625058,0.015073,0.006092,0.015278
2024-11-26 00:00:00-05:00,233.366440,0.009404,229.399252,225.276641,226.600095,1.035911,1.029860,0.029700,0.007055,10.751953,...,0.011012,0.977339,0,74.215693,1.132539,0.253579,0.878960,0.009530,0.007414,0.009600
2024-11-27 00:00:00-05:00,233.237381,-0.000553,230.576703,225.528953,226.887658,1.034179,1.027986,0.025895,0.022114,9.739319,...,0.010382,0.722355,0,68.024384,1.480424,0.498948,0.981476,0.008002,0.001962,0.008041
2024-11-29 00:00:00-05:00,235.620102,0.010216,232.326004,226.108163,227.060634,1.042068,1.037697,0.038552,0.051707,9.044373,...,0.009501,0.638891,0,72.073274,1.926187,0.784396,1.141791,0.016180,0.010732,0.016412
2024-12-02 00:00:00-05:00,237.863815,0.009523,234.255997,226.948315,227.291772,1.048097,1.046513,0.042285,0.076011,14.484879,...,0.008845,1.100970,0,83.362354,2.432467,1.114010,1.318457,0.015151,0.009778,0.015306

In [19]:
data_clean[feature_columns].tail()

,Close,Daily_Return,MA_5,MA_20,MA_50,Price_to_MA20,Price_to_MA50,Return_5D,Return_20D,Momentum_10D,...,Volatility_20D,Volume_Ratio,High_Volume_Flag,RSI_14,MACD,MACD_Signal,MACD_Histogram,Price_Range,Open_Close_Return,High_Low_Pct
Date,,,,,,,,,,,,,,,,,,,,,
2026-09-11 00:00:00-04:00,332.269989,0.017454,322.073999,316.625998,317.830374,1.049408,1.045432,0.012370,0.088482,17.690002,...,0.015035,1.192404,0,70.618906,3.265371,1.950648,1.314722,0.029855,0.014720,0.030402
2026-09-14 00:00:00-04:00,333.079987,0.002438,324.695996,317.983498,318.324693,1.047476,1.046353,0.040973,0.088746,13.379974,...,0.015034,0.911427,0,70.523448,3.970020,2.354523,1.615497,0.012490,-0.005108,0.012555
2026-09-15 00:00:00-04:00,331.339996,-0.005224,327.719995,319.270998,318.703681,1.037802,1.039649,0.047815,0.084263,14.489990,...,0.015140,0.742400,0,68.906524,4.338051,2.751228,1.586823,0.010352,0.003635,0.010446
2026-09-16 00:00:00-04:00,332.410004,0.003229,331.133997,320.389998,319.144035,1.037517,1.041567,0.054132,0.072187,7.279999,...,0.014942,0.857513,0,67.484315,4.662314,3.133446,1.528869,0.014380,-0.000361,0.014454
2026-09-17 00:00:00-04:00,333.070007,0.001986,332.433997,321.201999,319.543036,1.036949,1.042332,0.019904,0.051258,8.110016,...,0.014306,0.201684,0,67.200010,4.915885,3.489933,1.425952,0.016172,-0.005034,0.016313

In [20]:
data_clean

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Daily_Return,Price_Change,Price_Change_Pct,...,Volume_MA_20,Volume_Ratio,High_Volume_Flag,RSI_14,MACD,MACD_Signal,MACD_Histogram,Price_Range,Open_Close_Return,High_Low_Pct
Date,,,,,,,,,,,,,,,,,,,,,
2024-11-25 00:00:00-05:00,229.792416,231.569513,228.084806,231.192245,90152800,0.0,0.0,0.013051,1.399830,0.006092,...,46524025.0,1.937769,1,69.706490,0.658897,0.033839,0.625058,0.015073,0.006092,0.015278
2024-11-26 00:00:00-05:00,231.648908,233.872775,231.648908,233.366440,45986200,0.0,0.0,0.009404,1.717531,0.007414,...,47052475.0,0.977339,0,74.215693,1.132539,0.253579,0.878960,0.009530,0.007414,0.009600
2024-11-27 00:00:00-05:00,232.780704,233.991915,232.125455,233.237381,33498400,0.0,0.0,-0.000553,0.456677,0.001962,...,46373850.0,0.722355,0,68.024384,1.480424,0.498948,0.981476,0.008002,0.001962,0.008041
2024-11-29 00:00:00-05:00,233.118254,236.096639,232.284309,235.620102,28481400,0.0,0.0,0.010216,2.501848,0.010732,...,44579415.0,0.638891,0,72.073274,1.926187,0.784396,1.141791,0.016180,0.010732,0.016412
2024-12-02 00:00:00-05:00,235.560538,239.055167,235.451330,237.863815,48137100,0.0,0.0,0.009523,2.303277,0.009778,...,43722435.0,1.100970,0,83.362354,2.432467,1.114010,1.318457,0.015151,0.009778,0.015306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-11 00:00:00-04:00,327.450012,336.220001,326.299988,332.269989,50716900,0.0,0.0,0.017454,4.819977,0.014720,...,42533320.0,1.192404,0,70.618906,3.265371,1.950648,1.314722,0.029855,0.014720,0.030402
2026-09-14 00:00:00-04:00,334.790009,335.500000,331.339996,333.079987,39269100,0.0,0.0,0.002438,-1.710022,-0.005108,...,43085305.0,0.911427,0,70.523448,3.970020,2.354523,1.615497,0.012490,-0.005108,0.012555
2026-09-15 00:00:00-04:00,330.140015,331.779999,328.350006,331.339996,31748200,0.0,0.0,-0.005224,1.199982,0.003635,...,42764250.0,0.742400,0,68.906524,4.338051,2.751228,1.586823,0.010352,0.003635,0.010446
2026-09-16 00:00:00-04:00,332.529999,335.480011,330.700012,332.410004,35920400,0.0,0.0,0.003229,-0.119995,-0.000361,...,41889045.0,0.857513,0,67.484315,4.662314,3.133446,1.528869,0.014380,-0.000361,0.014454
2026-09-17 00:00:00-04:00,334.755005,335.579987,330.193695,333.070007,8019896,0.0,0.0,0.001986,-1.684998,-0.005034,...,39764759.8,0.201684,0,67.200010,4.915885,3.489933,1.425952,0.016172,-0.005034,0.016313

In [21]:
data_clean["Target_Return_1D"] = (
    data_clean["Close"].shift(-1) / data_clean["Close"]
) - 1

data_clean[[
    "Close",
    "Target_Return_1D"
]].tail()

                                Close  Target_Return_1D
Date
2026-09-11 00:00:00-04:00  332.269989          0.002438
2026-09-14 00:00:00-04:00  333.079987         -0.005224
2026-09-15 00:00:00-04:00  331.339996          0.003229
2026-09-16 00:00:00-04:00  332.410004          0.001986
2026-09-17 00:00:00-04:00  333.070007               NaN

In [22]:
data_clean["Target_Up"] = (
    data_clean["Target_Return_1D"] > 0
).astype(int)

data_clean[[
    "Close",
    "Target_Return_1D",
    "Target_Up"
]].tail()

                                Close  Target_Return_1D  Target_Up
Date
2026-09-11 00:00:00-04:00  332.269989          0.002438          1
2026-09-14 00:00:00-04:00  333.079987         -0.005224          0
2026-09-15 00:00:00-04:00  331.339996          0.003229          1
2026-09-16 00:00:00-04:00  332.410004          0.001986          1
2026-09-17 00:00:00-04:00  333.070007               NaN          0

In [23]:
data_clean = data_clean.dropna(
    subset=["Target_Return_1D"]
).copy()

print("Final dataset shape:", data_clean.shape)
print("Missing target values:")
print(data_clean[[
    "Target_Return_1D",
    "Target_Up"
]].isnull().sum())

Final dataset shape: (452, 33)
Missing target values:
Target_Return_1D    0
Target_Up           0
dtype: int64

In [24]:
print(data_clean["Target_Up"].value_counts())

print("\nTarget proportions:")
print(
    data_clean["Target_Up"]
    .value_counts(normalize=True)
    .sort_index()
)

Target_Up
1    243
0    209
Name: count, dtype: int64

Target proportions:
Target_Up
0    0.462389
1    0.537611
Name: proportion, dtype: float64

In [25]:
target_columns = [
    "Target_Return_1D",
    "Target_Up"
]

X = data_clean[feature_columns].copy()
y = data_clean["Target_Up"].copy()

print("Feature shape:", X.shape)
print("Target shape:", y.shape)
print("Feature columns:")
print(X.columns.tolist())

Feature shape: (452, 21)
Target shape: (452,)
Feature columns:
['Close', 'Daily_Return', 'MA_5', 'MA_20', 'MA_50', 'Price_to_MA20', 'Price_to_MA50', 'Return_5D', 'Return_20D', 'Momentum_10D', 'Volatility_5D', 'Volatility_20D', 'Volume_Ratio', 'High_Volume_Flag', 'RSI_14', 'MACD', 'MACD_Signal', 'MACD_Histogram', 'Price_Range', 'Open_Close_Return', 'High_Low_Pct']

In [26]:
split_index = int(len(data_clean) * 0.8)

X_train = X.iloc[:split_index].copy()
X_test = X.iloc[split_index:].copy()

y_train = y.iloc[:split_index].copy()
y_test = y.iloc[split_index:].copy()

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

print("\nTraining period:")
print(data_clean.index[0], "to", data_clean.index[split_index - 1])

print("\nTesting period:")
print(data_clean.index[split_index], "to", data_clean.index[-1])

Training features: (361, 21)
Testing features: (91, 21)
Training target: (361,)
Testing target: (91,)

Training period:
2024-11-25 00:00:00-05:00 to 2026-05-06 00:00:00-04:00

Testing period:
2026-05-07 00:00:00-04:00 to 2026-09-16 00:00:00-04:00

In [27]:
print("Training target distribution:")
print(y_train.value_counts(normalize=True).sort_index())

print("\nTesting target distribution:")
print(y_test.value_counts(normalize=True).sort_index())

Training target distribution:
Target_Up
0    0.468144
1    0.531856
Name: proportion, dtype: float64

Testing target distribution:
Target_Up
0    0.43956
1    0.56044
Name: proportion, dtype: float64

In [28]:
from sklearn.metrics import accuracy_score

majority_class = y_train.mode()[0]

baseline_predictions = [
    majority_class
] * len(y_test)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_predictions
)

print("Majority class:", majority_class)
print(f"Baseline accuracy: {baseline_accuracy:.2%}")

Majority class: 1
Baseline accuracy: 56.04%

In [31]:
data_clean.to_csv(
    "../data/equlens_engineered_features.csv"
)